export const ActionTypes = {
    FETCH_POSTS: 'FETCH_POSTS',
    FETCH_USERS: 'FETCH_USERS',
    FETCH_COMMENTS: 'FETCH_COMMENTS',
    FETCH_PHOTOS: 'FETCH_PHOTOS',
    REMOVE_POSTS: 'REMOVE_POSTS',
}